### ISSUE TITLE
Помощь в проекте

### ISSUE THREAD

**Issue by laion220995** [vrizo/uibook#2]
Привет.
Хочу помочь в развитии проекта. Какие задачи ты видишь приоритетными? С чем можно помочь?

**Comment by vrizo** [comment]
Hi, @laion220995 !

Glad to hear! Do you want to work with code, marketing or design? 

I have a plan file. Sorry, it is quite messy, because I didn't expect any contributors to this project:
https://github.com/vrizo/uibook/blob/master/PLAN.md

There are some pretty simple JS tasks for introduction to the project, such as:
- format example as JSX in lib/stringify. This file generates an example based on props. It uses "hyperscript" style now because I used to use it on my work (`h(Component, {}, children)`).
- test passing of Immutable JS as prop (lib/stringify)
- think of a way how to use Uibook with `create-react-app` (it doesn't allow modifying of webpack config)

Feel free to contact me here or by email kb@kernel-it.ru.

**Comment by laion220995** [comment]
Good, i try to work with code :D
I'll think about these tasks

**Comment by laion220995** [comment]
For now, close the task

Open new with PR :)
