### ISSUE TITLE
Live reload for uibook page

### ISSUE THREAD

**Issue by monochromer** [vrizo/uibook#4]
How to make live-reload on uibook page when changing files?

**Comment by vrizo** [comment]
Hi, @monochromer !

Thanks for your question. The feature is not implemented yet, I'll add it to plan. I'm on vacation right now, so it's gonna take some time.

**Comment by vrizo** [comment]
Hi, @monochromer !

Sorry for the long answer. The research took much more time than I expected. The new Uibook v.0.5.5 includes hot reload feature. It's necessary to enable this option in Uibook Controller:

_uibook-controller.js_
```
new UibookPlugin({
  …
  hot: true
})
```

<img src="https://media.amplifr.com/images/social_images/013/372/329/img.gif" alt="uibook hot reload" width="844" height="490" />

Please let me know if doesn't work because I'm not sure in the code :)
